site_name: RingCentral SDK for C#
site_url: https://github.com/ringcentral/ringcentral-csharp
repo_url: https://github.com/ringcentral/ringcentral-csharp.git
docs_dir: docs
theme: readthedocs
pages:
# Introduction:
- ['index.md', 'Overview', 'RingCentral SDK']

## Initialization
- ['usage/initialization/Initialization.md', 'Initialization', 'Initialization']

## Authorization:
- ['usage/authorization/Authorization.md', 'Authorization', 'Authorization']

## Message Store:
- ['usage/message-store/Message-Store.md', 'Message Store', 'Message Store']
