site_name: RingCentral SDK for C#
site_url: https://github.com/ringcentral/ringcentral-csharp
repo_url: https://github.com/ringcentral/ringcentral-csharp.git
docs_dir: docs
theme: readthedocs
pages:
- Quickstart: 'index.md'
- User Guide:
    - 'Initialization': 'usage/initialization/Initialization.md'
    - 'Authorization': 'usage/authorization/Authorization.md'
    - 'Message Store': 'usage/message-store/Message-Store.md'
    - 'Subscriptions': 'usage/notifications/Subscriptions.md'
